language: ruby
rvm:
- 2.3.6
- 2.4.2
sudo: false
cache:
  bundler: true
  yarn: true
  directories:
  - vendor/assets/bower/bower_components
addons:
  postgresql: '9.4'
env:
  matrix:
  - TEST_SUITE=spec
  - TEST_SUITE=spec:javascript
  - TEST_SUITE=spec:compile
  - TEST_SUITE=spec:jest
matrix:
  exclude:
  - rvm: 2.4.2
    env: TEST_SUITE=spec:javascript
  - rvm: 2.4.2
    env: TEST_SUITE=spec:compile
  - rvm: 2.4.2
    env: TEST_SUITE=spec:jest
bundler_args: "--no-deployment"
before_install: source tools/ci/before_install.sh
before_script: bundle exec rake $TEST_SUITE:setup
script: bundle exec rake $TEST_SUITE
before_cache:
- cp bower.json vendor/assets/bower/bower_components
after_script: source tools/ci/after_install.sh
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/9a9f972a1225d28e0f05
    on_success: change
    on_failure: always
    on_start: never
