language: ruby
rvm:
- '2.3.1'
sudo: false
cache:
  bundler: true
  directories:
  - vendor/assets/bower_components
addons:
  postgresql: '9.4'
env:
  matrix:
  - TEST_SUITE=test
  - TEST_SUITE=test:javascript
before_install: source tools/ci/before_install.sh
before_script: bundle exec rake $TEST_SUITE:setup
script: bundle exec rake $TEST_SUITE
before_cache:
- mkdir -p vendor/assets
- mv spec/manageiq/vendor/assets/bower_components vendor/assets
- cp bower.json vendor/assets/bower_components
after_script: if [ "$TEST_SUITE" = "test" ]; then bundle exec codeclimate-test-reporter; fi
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/9a9f972a1225d28e0f05
    on_success: change
    on_failure: always
    on_start: never
