---
language: ruby
python: '2.7'
rvm:
- 2.6.6
cache:
  bundler: true
  yarn: true
  timeout: 600
addons:
  postgresql: '10'
  chrome: beta
env:
  matrix:
  - TEST_SUITE=spec
  - TEST_SUITE=spec:routes
  - TEST_SUITE=spec:javascript
  - TEST_SUITE=spec:compile
  - TEST_SUITE=spec:jest
  - TEST_SUITE=spec:debride
bundler_args: "--no-deployment"
before_install: source bin/ci/before_install.sh
install: bin/setup
before_script: source bin/ci/before_script.sh
after_script: source bin/ci/after_script.sh
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/9a9f972a1225d28e0f05
    on_success: change
    on_failure: always
    on_start: never
